# Generated by Django 4.2.2 on 2023-06-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='duration_minutes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='is_am',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
