# Generated by Django 4.2.2 on 2023-06-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_city_room_city'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
    ]
