# Generated by Django 4.2.2 on 2023-06-22 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_city_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_am',
        ),
    ]
