# Generated by Django 4.2.2 on 2023-06-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_message_options_alter_room_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='start_time',
        ),
        migrations.AddField(
            model_name='room',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
